FROM --platform=linux/amd64 node:22-alpine AS deps
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci

FROM --platform=linux/amd64 node:22-alpine AS builder
WORKDIR /app
ENV NEXT_TELEMETRY_DISABLED=1
ARG NEXT_PUBLIC_API_URL
ARG NEXT_PUBLIC_SITE_URL
ARG NEXT_PUBLIC_ADMIN_URL
ARG NEXT_PUBLIC_FORMS_ADMIN_URL
ARG NEXT_PUBLIC_MAIL_URL
ARG NEXT_PUBLIC_CORE_API_URL
ARG NEXT_PUBLIC_SHORT_ORIGIN
ARG NEXT_PUBLIC_ARGE_URL
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_SITE_URL=$NEXT_PUBLIC_SITE_URL
ENV NEXT_PUBLIC_ADMIN_URL=$NEXT_PUBLIC_ADMIN_URL
ENV NEXT_PUBLIC_FORMS_ADMIN_URL=$NEXT_PUBLIC_FORMS_ADMIN_URL
ENV NEXT_PUBLIC_MAIL_URL=$NEXT_PUBLIC_MAIL_URL
ENV NEXT_PUBLIC_CORE_API_URL=$NEXT_PUBLIC_CORE_API_URL
ENV NEXT_PUBLIC_SHORT_ORIGIN=$NEXT_PUBLIC_SHORT_ORIGIN
ENV NEXT_PUBLIC_ARGE_URL=$NEXT_PUBLIC_ARGE_URL
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN test -n "$NEXT_PUBLIC_API_URL" \
    && test -n "$NEXT_PUBLIC_SITE_URL" \
    && test -n "$NEXT_PUBLIC_ADMIN_URL" \
    && test -n "$NEXT_PUBLIC_FORMS_ADMIN_URL" \
    && test -n "$NEXT_PUBLIC_MAIL_URL" \
    && test -n "$NEXT_PUBLIC_CORE_API_URL" \
    && test -n "$NEXT_PUBLIC_SHORT_ORIGIN" \
    && test -n "$NEXT_PUBLIC_ARGE_URL" \
    && npm run build

FROM --platform=linux/amd64 node:22-alpine
WORKDIR /app
ENV NODE_ENV=production NEXT_TELEMETRY_DISABLED=1 PORT=3000 HOSTNAME=0.0.0.0
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static
EXPOSE 3000
CMD ["node", "server.js"]
